### ISSUE TITLE
Enabling issues

### ISSUE THREAD

**Issue by simondel** [OpenSourceSpringCleaning/OpenSourceSpringCleaning.github.io#2]
The website says:

**As a maintainer**

- (If not already done) Enable issues in the repository’s settings page.

How do I do this? This is my settings page:
![image](https://cloud.githubusercontent.com/assets/4221997/25748937/2edd38bc-31ad-11e7-9314-84ef4dc5988a.png)

**Comment by MichielCuijpers** [comment]
Aha, thanks, we will make that more clear, we mean the repository's settings page on GitHub.
![enable issues](https://cloud.githubusercontent.com/assets/18576001/25749172/e606be64-31ad-11e7-8669-4993ca9e0760.jpg)

**Comment by simondel** [comment]
Fixed with 2c9e8a5

**Comment by MichielCuijpers** [comment]
Thanks for asking @simondel, there were probably others with the same question.
